// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_EUhAtAEsq8i_vD_54ZNC6R4dBYLNYjE',
    databaseURL: 'https://planejamentofinanceiro-faa6c-default-rtdb.firebaseio.com/',
    appId: '1:929166352594:web:624723a2b485102ec98d0b',
    messagingSenderId: '929166352594',
    projectId: 'planejamentofinanceiro-faa6c',
    authDomain: 'planejamentofinanceiro-faa6c.firebaseapp.com',
    storageBucket: 'planejamentofinanceiro-faa6c.firebasestorage.app',
    measurementId: 'G-YHQ9CVG0DP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALx5Hg6o28dMnYRA-rU8BhXAME9RlUinQ',
    appId: '1:929166352594:android:c0b609db6ef6ef37c98d0b',
    messagingSenderId: '929166352594',
    projectId: 'planejamentofinanceiro-faa6c',
    storageBucket: 'planejamentofinanceiro-faa6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgQTKRNeZo_wH8fp-HgaIjn8-UvjNs2zk',
    appId: '1:929166352594:ios:6a3830665ad0c1dfc98d0b',
    messagingSenderId: '929166352594',
    projectId: 'planejamentofinanceiro-faa6c',
    storageBucket: 'planejamentofinanceiro-faa6c.firebasestorage.app',
    iosBundleId: 'com.example.planejamentoFinanceiro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgQTKRNeZo_wH8fp-HgaIjn8-UvjNs2zk',
    appId: '1:929166352594:ios:6a3830665ad0c1dfc98d0b',
    messagingSenderId: '929166352594',
    projectId: 'planejamentofinanceiro-faa6c',
    storageBucket: 'planejamentofinanceiro-faa6c.firebasestorage.app',
    iosBundleId: 'com.example.planejamentoFinanceiro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_EUhAtAEsq8i_vD_54ZNC6R4dBYLNYjE',
    appId: '1:929166352594:web:9471322ed971e4d5c98d0b',
    messagingSenderId: '929166352594',
    projectId: 'planejamentofinanceiro-faa6c',
    authDomain: 'planejamentofinanceiro-faa6c.firebaseapp.com',
    storageBucket: 'planejamentofinanceiro-faa6c.firebasestorage.app',
    measurementId: 'G-TD1J5Y06M7',
  );
}
